<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\Hash;

use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            ['name' =>'23 DE ENERO', 'email' => '23deenero_gmvmpq@correo.com', 'password' => Hash::make('kca5CvR'), 'parroquia_id' => '10111', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'ALTAGRACIA', 'email' => 'altagracia_gmvmpq@correo.com', 'password' => Hash::make('BiEMz4f'), 'parroquia_id' => '10101', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'ANTIMANO', 'email' => 'antimano_gmvmpq@correo.com', 'password' => Hash::make('tik40Ur'), 'parroquia_id' => '10112', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'CARICUAO', 'email' => 'caricuao_gmvmpq@correo.com', 'password' => Hash::make('UxLtKSK'), 'parroquia_id' => '10117', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'CATEDRAL', 'email' => 'catedral_gmvmpq@correo.com', 'password' => Hash::make('0uq6vRt'), 'parroquia_id' => '10103', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'COCHE', 'email' => 'coche_gmvmpq@correo.com', 'password' => Hash::make('KeMXnJy'), 'parroquia_id' => '10119', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'EL JUNQUITO', 'email' => 'eljunquito_gmvmpq@correo.com', 'password' => Hash::make('JRNiVne'), 'parroquia_id' => '10118', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'EL PARAISO', 'email' => 'elparaiso_gmvmpq@correo.com', 'password' => Hash::make('3QUYNXQ'), 'parroquia_id' => '10122', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'EL RECREO', 'email' => 'elrecreo_gmvmpq@correo.com', 'password' => Hash::make('ZiVDWnh'), 'parroquia_id' => '10113', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'ELVALLE', 'email' => 'elvalle_gmvmpq@correo.com', 'password' => Hash::make('aA13y3D'), 'parroquia_id' => '10114', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'LA CANDELARIA', 'email' => 'candelaria_gmvmpq@correo.com', 'password' => Hash::make('59FGfcB'), 'parroquia_id' => '10102', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'LA PASTORA', 'email' => 'lapastora_gmvmpq@correo.com', 'password' => Hash::make('DQCE72Y'), 'parroquia_id' => '10104', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'LA VEGA', 'email' => 'lavega_gmvmpq@correo.com', 'password' => Hash::make('9M3zZfL'), 'parroquia_id' => '10115', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'MACARAO', 'email' => 'macarao_gmvmpq@correo.com', 'password' => Hash::make('LLx2cb8'), 'parroquia_id' => '10116', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SAN AGUSTIN', 'email' => 'sanagustin_gmvmpq@correo.com', 'password' => Hash::make('CF9MNUQ'), 'parroquia_id' => '10105', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SAN BERNARDINO', 'email' => 'sanbernardino_gmvmpq@correo.com', 'password' => Hash::make('qr6ibHC'), 'parroquia_id' => '10121', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SAN JOSE', 'email' => 'sanjose_gmvmpq@correo.com', 'password' => Hash::make('UTTqLpN'), 'parroquia_id' => '10106', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SAN JUAN', 'email' => 'sanjuan_gmvmpq@correo.com', 'password' => Hash::make('BUH39wi'), 'parroquia_id' => '10107', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SAN PEDRO', 'email' => 'sanpedro_gmvmpq@correo.com', 'password' => Hash::make('AAk2HHq'), 'parroquia_id' => '10120', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SANTA ROSALIA', 'email' => 'santarosalia_gmvmpq@correo.com', 'password' => Hash::make('jNTAvz9'), 'parroquia_id' => '10108', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SANTA TERESA', 'email' => 'santateresa_gmvmpq@correo.com', 'password' => Hash::make('BTGTcqA'), 'parroquia_id' => '10109', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'SUCRE', 'email' => 'sucre_gmvmpq@correo.com', 'password' => Hash::make('jEFAci8'), 'parroquia_id' => '10110', 'mision_id' => '1', 'nivel_id' => '3'],
            ['name' =>'23 DE ENERO', 'email' => '23deenero_gmvj@correo.com', 'password' => Hash::make('X7AbFcN'), 'parroquia_id' => '10111', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'ALTAGRACIA', 'email' => 'altagracia_gmvj@correo.com', 'password' => Hash::make('DPxuDWM'), 'parroquia_id' => '10101', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'ANTIMANO', 'email' => 'antimano_gmvj@correo.com', 'password' => Hash::make('20HuAr8'), 'parroquia_id' => '10112', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'CARICUAO', 'email' => 'caricuao_gmvj@correo.com', 'password' => Hash::make('UWnraNe'), 'parroquia_id' => '10117', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'CATEDRAL', 'email' => 'catedral_gmvj@correo.com', 'password' => Hash::make('37ACQFA'), 'parroquia_id' => '10103', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'COCHE', 'email' => 'coche_gmvj@correo.com', 'password' => Hash::make('wGnMjdZ'), 'parroquia_id' => '10119', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'EL JUNQUITO', 'email' => 'eljunquito_gmvj@correo.com', 'password' => Hash::make('AJumiQb'), 'parroquia_id' => '10118', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'EL PARAISO', 'email' => 'elparaiso_gmvj@correo.com', 'password' => Hash::make('qJZbW1b'), 'parroquia_id' => '10122', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'EL RECREO', 'email' => 'elrecreo_gmvj@correo.com', 'password' => Hash::make('YWJyRCA'), 'parroquia_id' => '10113', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'ELVALLE', 'email' => 'elvalle_gmvj@correo.com', 'password' => Hash::make('vvyLmqi'), 'parroquia_id' => '10114', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'LA CANDELARIA', 'email' => 'candelaria_gmvj@correo.com', 'password' => Hash::make('8CX6QKh'), 'parroquia_id' => '10102', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'LA PASTORA', 'email' => 'lapastora_gmvj@correo.com', 'password' => Hash::make('hizi16A'), 'parroquia_id' => '10104', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'LA VEGA', 'email' => 'lavega_gmvj@correo.com', 'password' => Hash::make('dFVWUhh'), 'parroquia_id' => '10115', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'MACARAO', 'email' => 'macarao_gmvj@correo.com', 'password' => Hash::make('2x49yj7'), 'parroquia_id' => '10116', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SAN AGUSTIN', 'email' => 'sanagustin_gmvj@correo.com', 'password' => Hash::make('pbGW22Q'), 'parroquia_id' => '10105', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SAN BERNARDINO', 'email' => 'sanbernardino_gmvj@correo.com', 'password' => Hash::make('3Jq7AhY'), 'parroquia_id' => '10121', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SAN JOSE', 'email' => 'sanjose_gmvj@correo.com', 'password' => Hash::make('Vnmd2uB'), 'parroquia_id' => '10106', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SAN JUAN', 'email' => 'sanjuan_gmvj@correo.com', 'password' => Hash::make('ffTU9NE'), 'parroquia_id' => '10107', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SAN PEDRO', 'email' => 'sanpedro_gmvj@correo.com', 'password' => Hash::make('9kihVra'), 'parroquia_id' => '10120', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SANTA ROSALIA', 'email' => 'santarosalia_gmvj@correo.com', 'password' => Hash::make('2XL223L'), 'parroquia_id' => '10108', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SANTA TERESA', 'email' => 'santateresa_gmvj@correo.com', 'password' => Hash::make('bXZ30YX'), 'parroquia_id' => '10109', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'SUCRE', 'email' => 'sucre_gmvj@correo.com', 'password' => Hash::make('wSVP85C'), 'parroquia_id' => '10110', 'mision_id' => '2', 'nivel_id' => '3'],
            ['name' =>'23 DE ENERO', 'email' => '23deenero_gmayap@correo.com', 'password' => Hash::make('BFAVGT6'), 'parroquia_id' => '10111', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'ALTAGRACIA', 'email' => 'altagracia_gmayap@correo.com', 'password' => Hash::make('18j4FC1'), 'parroquia_id' => '10101', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'ANTIMANO', 'email' => 'antimano_gmayap@correo.com', 'password' => Hash::make('8JJJ4yT'), 'parroquia_id' => '10112', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'CARICUAO', 'email' => 'caricuao_gmayap@correo.com', 'password' => Hash::make('THcp7Lu'), 'parroquia_id' => '10117', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'CATEDRAL', 'email' => 'catedral_gmayap@correo.com', 'password' => Hash::make('bgzv3HW'), 'parroquia_id' => '10103', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'COCHE', 'email' => 'coche_gmayap@correo.com', 'password' => Hash::make('3XpJAqz'), 'parroquia_id' => '10119', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'EL JUNQUITO', 'email' => 'eljunquito_gmayap@correo.com', 'password' => Hash::make('Fwbhgk4'), 'parroquia_id' => '10118', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'EL PARAISO', 'email' => 'elparaiso_gmayap@correo.com', 'password' => Hash::make('MAtMEFJ'), 'parroquia_id' => '10122', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'EL RECREO', 'email' => 'elrecreo_gmayap@correo.com', 'password' => Hash::make('edCiGWK'), 'parroquia_id' => '10113', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'ELVALLE', 'email' => 'elvalle_gmayap@correo.com', 'password' => Hash::make('prfTnQT'), 'parroquia_id' => '10114', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'LA CANDELARIA', 'email' => 'candelaria_gmayap@correo.com', 'password' => Hash::make('H7VWMfL'), 'parroquia_id' => '10102', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'LA PASTORA', 'email' => 'lapastora_gmayap@correo.com', 'password' => Hash::make('nw30Pxu'), 'parroquia_id' => '10104', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'LA VEGA', 'email' => 'lavega_gmayap@correo.com', 'password' => Hash::make('GEXJp4h'), 'parroquia_id' => '10115', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'MACARAO', 'email' => 'macarao_gmayap@correo.com', 'password' => Hash::make('x8VDDQw'), 'parroquia_id' => '10116', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SAN AGUSTIN', 'email' => 'sanagustin_gmayap@correo.com', 'password' => Hash::make('55r4anM'), 'parroquia_id' => '10105', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SAN BERNARDINO', 'email' => 'sanbernardino_gmayap@correo.com', 'password' => Hash::make('5EPSp89'), 'parroquia_id' => '10121', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SAN JOSE', 'email' => 'sanjose_gmayap@correo.com', 'password' => Hash::make('zFkjXeA'), 'parroquia_id' => '10106', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SAN JUAN', 'email' => 'sanjuan_gmayap@correo.com', 'password' => Hash::make('bHxiYTM'), 'parroquia_id' => '10107', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SAN PEDRO', 'email' => 'sanpedro_gmayap@correo.com', 'password' => Hash::make('R4cpUnA'), 'parroquia_id' => '10120', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SANTA ROSALIA', 'email' => 'santarosalia_gmayap@correo.com', 'password' => Hash::make('Rdnhm6V'), 'parroquia_id' => '10108', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SANTA TERESA', 'email' => 'santateresa_gmayap@correo.com', 'password' => Hash::make('9eiNjw6'), 'parroquia_id' => '10109', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'SUCRE', 'email' => 'sucre_gmayap@correo.com', 'password' => Hash::make('WAzbnFH'), 'parroquia_id' => '10110', 'mision_id' => '3', 'nivel_id' => '3'],
            ['name' =>'23 DE ENERO', 'email' => '23deenero_gmijs@correo.com', 'password' => Hash::make('fnPj9Wc'), 'parroquia_id' => '10111', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'ALTAGRACIA', 'email' => 'altagracia_gmijs@correo.com', 'password' => Hash::make('H7MDwWA'), 'parroquia_id' => '10101', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'ANTIMANO', 'email' => 'antimano_gmijs@correo.com', 'password' => Hash::make('0x1kGbC'), 'parroquia_id' => '10112', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'CARICUAO', 'email' => 'caricuao_gmijs@correo.com', 'password' => Hash::make('xYqm0gU'), 'parroquia_id' => '10117', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'CATEDRAL', 'email' => 'catedral_gmijs@correo.com', 'password' => Hash::make('YWkcJLi'), 'parroquia_id' => '10103', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'COCHE', 'email' => 'coche_gmijs@correo.com', 'password' => Hash::make('UdawjQ0'), 'parroquia_id' => '10119', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'EL JUNQUITO', 'email' => 'eljunquito_gmijs@correo.com', 'password' => Hash::make('MSvPwMj'), 'parroquia_id' => '10118', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'EL PARAISO', 'email' => 'elparaiso_gmijs@correo.com', 'password' => Hash::make('6CWbvKK'), 'parroquia_id' => '10122', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'EL RECREO', 'email' => 'elrecreo_gmijs@correo.com', 'password' => Hash::make('BYrgh7j'), 'parroquia_id' => '10113', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'ELVALLE', 'email' => 'elvalle_gmijs@correo.com', 'password' => Hash::make('d0J1n6y'), 'parroquia_id' => '10114', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'LA CANDELARIA', 'email' => 'candelaria_gmijs@correo.com', 'password' => Hash::make('mDcmtL8'), 'parroquia_id' => '10102', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'LA PASTORA', 'email' => 'lapastora_gmijs@correo.com', 'password' => Hash::make('PEgW9pF'), 'parroquia_id' => '10104', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'LA VEGA', 'email' => 'lavega_gmijs@correo.com', 'password' => Hash::make('rFGWfxG'), 'parroquia_id' => '10115', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'MACARAO', 'email' => 'macarao_gmijs@correo.com', 'password' => Hash::make('1na62NL'), 'parroquia_id' => '10116', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SAN AGUSTIN', 'email' => 'sanagustin_gmijs@correo.com', 'password' => Hash::make('ze0ZtZ9'), 'parroquia_id' => '10105', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SAN BERNARDINO', 'email' => 'sanbernardino_gmijs@correo.com', 'password' => Hash::make('pwbj2i3'), 'parroquia_id' => '10121', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SAN JOSE', 'email' => 'sanjose_gmijs@correo.com', 'password' => Hash::make('i3YUW3d'), 'parroquia_id' => '10106', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SAN JUAN', 'email' => 'sanjuan_gmijs@correo.com', 'password' => Hash::make('WGbDgYj'), 'parroquia_id' => '10107', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SAN PEDRO', 'email' => 'sanpedro_gmijs@correo.com', 'password' => Hash::make('NUg2cSd'), 'parroquia_id' => '10120', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SANTA ROSALIA', 'email' => 'santarosalia_gmijs@correo.com', 'password' => Hash::make('jd6ZQS3'), 'parroquia_id' => '10108', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SANTA TERESA', 'email' => 'santateresa_gmijs@correo.com', 'password' => Hash::make('LxXay7N'), 'parroquia_id' => '10109', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'SUCRE', 'email' => 'sucre_gmijs@correo.com', 'password' => Hash::make('NNVQYJH'), 'parroquia_id' => '10110', 'mision_id' => '4', 'nivel_id' => '3'],
            ['name' =>'23 DE ENERO', 'email' => '23deenero_gmcti@correo.com', 'password' => Hash::make('PZ1Mj37'), 'parroquia_id' => '10111', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'ALTAGRACIA', 'email' => 'altagracia_gmcti@correo.com', 'password' => Hash::make('PHnyMhS'), 'parroquia_id' => '10101', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'ANTIMANO', 'email' => 'antimano_gmcti@correo.com', 'password' => Hash::make('5a1Bryh'), 'parroquia_id' => '10112', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'CARICUAO', 'email' => 'caricuao_gmcti@correo.com', 'password' => Hash::make('WQgiWTG'), 'parroquia_id' => '10117', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'CATEDRAL', 'email' => 'catedral_gmcti@correo.com', 'password' => Hash::make('pRYtL1g'), 'parroquia_id' => '10103', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'COCHE', 'email' => 'coche_gmcti@correo.com', 'password' => Hash::make('viPLCyY'), 'parroquia_id' => '10119', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'EL JUNQUITO', 'email' => 'eljunquito_gmcti@correo.com', 'password' => Hash::make('yf9D6AJ'), 'parroquia_id' => '10118', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'EL PARAISO', 'email' => 'elparaiso_gmcti@correo.com', 'password' => Hash::make('yFnJJwA'), 'parroquia_id' => '10122', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'EL RECREO', 'email' => 'elrecreo_gmcti@correo.com', 'password' => Hash::make('h1qpFVg'), 'parroquia_id' => '10113', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'ELVALLE', 'email' => 'elvalle_gmcti@correo.com', 'password' => Hash::make('VdmHWWQ'), 'parroquia_id' => '10114', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'LA CANDELARIA', 'email' => 'candelaria_gmcti@correo.com', 'password' => Hash::make('iHBj7vg'), 'parroquia_id' => '10102', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'LA PASTORA', 'email' => 'lapastora_gmcti@correo.com', 'password' => Hash::make('a17i8B4'), 'parroquia_id' => '10104', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'LA VEGA', 'email' => 'lavega_gmcti@correo.com', 'password' => Hash::make('qJeUM9Q'), 'parroquia_id' => '10115', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'MACARAO', 'email' => 'macarao_gmcti@correo.com', 'password' => Hash::make('Q3HyDtD'), 'parroquia_id' => '10116', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SAN AGUSTIN', 'email' => 'sanagustin_gmcti@correo.com', 'password' => Hash::make('trGpLFi'), 'parroquia_id' => '10105', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SAN BERNARDINO', 'email' => 'sanbernardino_gmcti@correo.com', 'password' => Hash::make('XSPeC4N'), 'parroquia_id' => '10121', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SAN JOSE', 'email' => 'sanjose_gmcti@correo.com', 'password' => Hash::make('rS3RqNv'), 'parroquia_id' => '10106', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SAN JUAN', 'email' => 'sanjuan_gmcti@correo.com', 'password' => Hash::make('6AE3BFc'), 'parroquia_id' => '10107', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SAN PEDRO', 'email' => 'sanpedro_gmcti@correo.com', 'password' => Hash::make('AghBXKY'), 'parroquia_id' => '10120', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SANTA ROSALIA', 'email' => 'santarosalia_gmcti@correo.com', 'password' => Hash::make('xN65FA6'), 'parroquia_id' => '10108', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SANTA TERESA', 'email' => 'santateresa_gmcti@correo.com', 'password' => Hash::make('rQ8aKXy'), 'parroquia_id' => '10109', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'SUCRE', 'email' => 'sucre_gmcti@correo.com', 'password' => Hash::make('anEQ7DJ'), 'parroquia_id' => '10110', 'mision_id' => '5', 'nivel_id' => '3'],
            ['name' =>'23 DE ENERO', 'email' => '23deenero_gmvm@correo.com', 'password' => Hash::make('yHDWBJK'), 'parroquia_id' => '10111', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'ALTAGRACIA', 'email' => 'altagracia_gmvm@correo.com', 'password' => Hash::make('U8a5hnq'), 'parroquia_id' => '10101', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'ANTIMANO', 'email' => 'antimano_gmvm@correo.com', 'password' => Hash::make('2DN6i3i'), 'parroquia_id' => '10112', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'CARICUAO', 'email' => 'caricuao_gmvm@correo.com', 'password' => Hash::make('rFQE7J9'), 'parroquia_id' => '10117', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'CATEDRAL', 'email' => 'catedral_gmvm@correo.com', 'password' => Hash::make('ixi9GPg'), 'parroquia_id' => '10103', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'COCHE', 'email' => 'coche_gmvm@correo.com', 'password' => Hash::make('kzw3fG1'), 'parroquia_id' => '10119', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'EL JUNQUITO', 'email' => 'eljunquito_gmvm@correo.com', 'password' => Hash::make('66A51gu'), 'parroquia_id' => '10118', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'EL PARAISO', 'email' => 'elparaiso_gmvm@correo.com', 'password' => Hash::make('qqrCiZ3'), 'parroquia_id' => '10122', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'EL RECREO', 'email' => 'elrecreo_gmvm@correo.com', 'password' => Hash::make('9LHm4J8'), 'parroquia_id' => '10113', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'ELVALLE', 'email' => 'elvalle_gmvm@correo.com', 'password' => Hash::make('Stdav0a'), 'parroquia_id' => '10114', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'LA CANDELARIA', 'email' => 'candelaria_gmvm@correo.com', 'password' => Hash::make('S8tE76H'), 'parroquia_id' => '10102', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'LA PASTORA', 'email' => 'lapastora_gmvm@correo.com', 'password' => Hash::make('Hbb0TVB'), 'parroquia_id' => '10104', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'LA VEGA', 'email' => 'lavega_gmvm@correo.com', 'password' => Hash::make('Fmykfkc'), 'parroquia_id' => '10115', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'MACARAO', 'email' => 'macarao_gmvm@correo.com', 'password' => Hash::make('0JiwJX9'), 'parroquia_id' => '10116', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SAN AGUSTIN', 'email' => 'sanagustin_gmvm@correo.com', 'password' => Hash::make('Xgj4AxE'), 'parroquia_id' => '10105', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SAN BERNARDINO', 'email' => 'sanbernardino_gmvm@correo.com', 'password' => Hash::make('WuR4faZ'), 'parroquia_id' => '10121', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SAN JOSE', 'email' => 'sanjose_gmvm@correo.com', 'password' => Hash::make('badivKe'), 'parroquia_id' => '10106', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SAN JUAN', 'email' => 'sanjuan_gmvm@correo.com', 'password' => Hash::make('6g4nAzM'), 'parroquia_id' => '10107', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SAN PEDRO', 'email' => 'sanpedro_gmvm@correo.com', 'password' => Hash::make('DCbECAE'), 'parroquia_id' => '10120', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SANTA ROSALIA', 'email' => 'santarosalia_gmvm@correo.com', 'password' => Hash::make('1d66tdR'), 'parroquia_id' => '10108', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SANTA TERESA', 'email' => 'santateresa_gmvm@correo.com', 'password' => Hash::make('xBrA5TE'), 'parroquia_id' => '10109', 'mision_id' => '6', 'nivel_id' => '3'],
            ['name' =>'SUCRE', 'email' => 'sucre_gmvm@correo.com', 'password' => Hash::make('3hx6Tgg'), 'parroquia_id' => '10110', 'mision_id' => '6', 'nivel_id' => '3'],
        ]);

        User::factory()->create(['name' =>'GRAN MISIÓN VIVA VENEZUELA MI PATRIA QUERIDA', 'email' => 'gmvmpq@correo.com', 'password' => Hash::make('PtbaTJm'),'mision_id' => '1', 'nivel_id' => '2']);
        User::insert(['name' =>'GRAN MISIÓN VENEZUELA JOVEN', 'email' => 'gmvj@correo.com', 'password' => Hash::make('y4wqSC7'),'mision_id' => '2', 'nivel_id' => '2']);
        User::insert(['name' =>'GRAN MISIÓN ABUELOS Y ABUELAS DE LA PATRIA', 'email' => 'gmayap@correo.com', 'password' => Hash::make('m34UpQA'),'mision_id' => '3', 'nivel_id' => '2']);
        User::insert(['name' =>'GRAN MISIÓN IGUALDAD Y JUSTICIA SOCIAL', 'email' => 'gmijs@correo.com', 'password' => Hash::make('3iqjG3P'),'mision_id' => '4', 'nivel_id' => '2']);
        User::insert(['name' =>'GRAN MISIÓN CIENCIA, TECNOLOGÍA E INNOVACIÓN', 'email' => 'gmcti@correo.com', 'password' => Hash::make('jDtM6Cd'),'mision_id' => '5', 'nivel_id' => '2']);
        User::insert(['name' =>'GRAN MISIÓN VENEZUELA MUJER', 'email' => 'gmvm@correo.com', 'password' => Hash::make('mHTiVAa'),'mision_id' => '6', 'nivel_id' => '2']);
    }
}
